version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: safety_admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: fraud_db_new
    ports:
      - "5435:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql